### ISSUE TITLE
Hangman, but instead of it choosing your topic, you can choose your own. For example, aminals, celebrities, places, etc... :3

### ISSUE THREAD

**Issue by smolbabykitty** [crazygmr101/StarStruck#14]

**Comment by crazygmr101** [comment]
@Naia-love you know of any api for this =/

**Comment by crazygmr101** [comment]
[f18594f](https://github.com/crazygmr101/StarStruck/commit/f18594f767958d23d40dd125726ef934b6a74e15) - Added [`config/hangman.json`](https://github.com/crazygmr101/StarStruck/blob/feature/games/config/hangman.json) with the words, and a playable hangman game, except the only category is animals at the moment.
